services:
  - type: web
    name: crud-laravel-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://crud-laravel-app.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: trolley.proxy.rlwy.net
      - key: DB_PORT
        value: 17359
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: dMvuGwJMwZoZsvmhoPdaTZyOtmqANbTP
